name: my_freezed_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  get: ^4.7.3
  # flutter_secure_storage: ^10.0.0
  dio: ^5.9.1
  google_fonts: ^8.0.1
  new_version_plus: ^1.0.1
  lottie: ^3.3.2
  flutter_svg: ^2.2.3
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.7
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  get_storage: ^2.1.1
  firebase_auth: ^6.1.4
  stacked_firebase_auth:
   git:
     url: https://github.com/NobleCT/firebase_auth.git
     ref: update-firebase-dependencies
  # flutter_facebook_auth: ^7.1.5
  firebase_core: ^4.4.0
  flutter_gen_runner: ^5.11.0 
  flutter_dotenv: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.0


flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/lottiefiles/
    - assets/svg/
    - lib/.env

